apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "sample"
  links:
    - url: https://alex7842.vercel.app
      title: Alex Dashboard 
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: value
spec:
  type: service
  owner: Alex
  lifecycle: experimental
